### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by gdevenyi** [hsborges/bibtex-normalizer#29]
This just got posed to reddit here: https://www.reddit.com/r/LaTeX/comments/6jub99/bibtexnormalizer_normalizing_bibtex_entries_to_a/

Yet I have very little idea what this project is or what it's goals are.

The README doesn't really say.

**Comment by paulo-carvalho** [comment]
Hi @gdevenyi ! Thank you for reporting this issue.

I've updated our README with images explaining how it works, step by step.

**Comment by gdevenyi** [comment]
Wonderful thanks!
