### ISSUE TITLE
Unhelpful error message (bug?)

### ISSUE THREAD

**Issue by wheerd** [hsborges/bibtex-normalizer#30]
I just tried it with [this bibliography file](https://github.com/wheerd/scipy_proceedings/blob/2017/papers/manuel_krebber/literature.bib). It did not seem to be able to parse it and I got the message "Your entry is incorrect, check one of the following, undefined line 1:
true" which was not very helpful.

**Comment by hsborges** [comment]
Hi @wheerd, thank you very much for reporting this issue :+1: 
I already fixed and pushed a new version to https://hsborges.github.io/bibtex-normalizer
Could you please test it again? Thanks.

**Comment by wheerd** [comment]
It works now, thanks a lot for the quick fix! ;)
