### ISSUE TITLE
Autocorrection with problems in author name ending with Jr

### ISSUE THREAD

**Issue by mtov** [hsborges/bibtex-normalizer#31]
Hi, 

See this entry:

@inproceedings{washburn2016went,
  title={What went right and what went wrong: an analysis of 155 postmortems from game development},
  author={Washburn Jr, Michael and Sathiyanarayanan, Pavithra and Nagappan, Meiyappan and Zimmermann, Thomas and Bird, Christian},
  booktitle={38th International Conference on Software Engineering Companion (ICSE)},
  pages={280--289},
  year={2016}
}

it was formatted to:

@inproceedings{washburn2016went,
  title = { What went right and what went wrong: an analysis of 155 postmortems from game development },
  author = { Michael Jr and Pavithra Sathiyanarayanan and Meiyappan Nagappan and Thomas Zimmermann and Christian Bird },
  booktitle = { 38th International Conference on Software Engineering Companion (ICSE) },
  pages = { 280--289 },
  year = { 2016 }
}

**Comment by hsborges** [comment]
Hi @mtov, thank you for reporting this issue :+1: 
I published a new version to fix this issue.
