### ISSUE TITLE
Failed for my bibtex

### ISSUE THREAD

**Issue by gabrielsmenezes** [hsborges/bibtex-normalizer#40]
Hi Professor Hudson, I ran the normalizer for my [BibTeX file](https://github.com/gabrielsmenezes/mybibtex/blob/main/main.bib)  and no message was displayed. I compared the text on the platform with my previous one and no changes were made. This is the screenshot of the browser console. 
![image](https://user-images.githubusercontent.com/40703319/167460001-a877738f-9ce1-456b-95c5-e99133535594.png)

Maybe the problem is the size of my bib (~100KB)

**Comment by hsborges** [comment]
Hey @gabrielsmenezes thanks for reporting this issue.
I found that the problem is caused by a line break on the following reference:

```bibtex
@journalarticle{ abnt9126,
    title={Engenharia de software - Qualidade de
produto Parte 1: Modelo de Qualidade},
    author={ABNT/CB-21 - Comitê Brasileiro de Computadores e Processamento de Dados},
    year={2003},
    publisher={ABNT–Associação Brasileira de
Normas Técnicas},
}
```
I'll be releasing a fix soon.

**Comment by gabrielsmenezes** [comment]
Nice @hsborges !! I just ran it again and it worked perfectly.

Thanks!

![image](https://user-images.githubusercontent.com/40703319/167633732-f28650aa-f2ab-4791-ba64-8edeb347f65d.png)
